import type {
  User,
  TemperatureTarget,
  GoodsReceipt,
  CleaningTask,
  SecondaryDlcItem,
  NonConformanceIncident,
  PestBaitStation,
  PestContractInfo,
  PestIntervention,
  PestInvoice,
  WasteLog,
  DdpAuditPoint,
  ApprovedProduct,
  AllergenItem,
} from '../types';

import baderAvatar from '../assets/avatars/bader_l.jpg';
import adelAvatar from '../assets/avatars/adel_b.jpg';
import hamzaAvatar from '../assets/avatars/hamza_m.jpg';

export const DEFAULT_USERS: User[] = [
  { id: 'u_bader', name: 'Bader L', role: 'Responsable', pin: '1234', avatarUrl: baderAvatar, avatarColor: '#3b82f6' },
  { id: 'u_adel', name: 'Adel B', role: 'Responsable', pin: '1234', avatarUrl: adelAvatar, avatarColor: '#f59e0b' },
  { id: 'u_hamza', name: 'Hamza M', role: 'Boulanger', pin: '1234', avatarUrl: hamzaAvatar, avatarColor: '#22c55e' },
  { id: 'u_said_n', name: 'Said N', role: 'Boulanger', pin: '1234', avatarColor: '#a855f7' },
  { id: 'u_said_dz', name: 'Said dz', role: 'Pâtissier', pin: '1234', avatarColor: '#ef4444' },
];
export const DEFAULT_TEMPERATURE_TARGETS: TemperatureTarget[] = [];

export const DEFAULT_CLEANING_TASKS: CleaningTask[] = [];

export const DEFAULT_RECEIPTS: GoodsReceipt[] = [];

export const DEFAULT_SECONDARY_DLC: SecondaryDlcItem[] = [
  {
    id: 'dlc_01',
    productName: 'Crème Pâtissière Vanille Bourbon',
    category: 'Pâtisserie',
    prepDate: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    durationHours: 48,
    expiryDate: new Date(Date.now() + 44 * 3600 * 1000).toISOString(),
    preparedBy: 'Sophie (Chef Pâtissière)',
    lotOriginal: 'Lait 4882 / OVO-9921',
    storageTemp: '+2°C à +4°C',
    notes: 'Refroidie immédiatement en cellule.',
  },
  {
    id: 'dlc_02',
    productName: 'Bouteille Blancs d’Œufs (Entamée)',
    category: 'Matière Première Ouverte',
    prepDate: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    durationHours: 24,
    expiryDate: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    preparedBy: 'Said dz',
    lotOriginal: 'OVO-9921',
    storageTemp: '+2°C à +4°C',
    notes: 'À consommer ou jeter d’ici demain matin.',
  }
];

export const DEFAULT_INCIDENTS: NonConformanceIncident[] = [
  {
    id: 'inc_01',
    title: 'Thermostat Vitrine Pâtisserie décalé',
    type: 'Panne Froid',
    severity: 'Moyenne',
    description: 'La vitrine affichait +7.2°C à 11h suite à forte chaleur en boutique.',
    correctiveAction: 'Gâteaux déplacés 20 min en chambre froide, thermostat réglé à +3°C, contrôle effectué à +4.1°C à 11h45.',
    reportedBy: 'Hamza M.',
    timestamp: '19/08/2026 11:30',
    status: 'Résolu',
    resolvedAt: '19/08/2026 11:50',
  }
];

// 🐭 Pièges Anti-Nuisibles
export const DEFAULT_PEST_STATIONS: PestBaitStation[] = [
  {
    id: 'pest_01',
    code: 'P-01',
    location: 'Fournil - Arrière du four à soles',
    type: 'Souris/Rats',
    status: 'Intact (RAS)',
    lastChecked: '27/05/2025 09:30',
    checkedBy: 'Adel B.',
    notes: 'Passage EDEN VERT 3D (Jérémy Claire) : Rodenticide anticoagulant vérifié, boîte verrouillée.',
  },
  {
    id: 'pest_02',
    code: 'P-02',
    location: 'Réserve - Angle stockage palettes farine',
    type: 'Souris/Rats',
    status: 'Intact (RAS)',
    lastChecked: '27/05/2025 09:35',
    checkedBy: 'Adel B.',
    notes: 'Passage EDEN VERT 3D : Zone stockage farine propre, appât sécurisé conforme.',
  },
  {
    id: 'pest_03',
    code: 'P-03',
    location: 'Labo Pâtisserie - Sous tour réfrigéré inox',
    type: 'Insectes/Cafards',
    status: 'Intact (RAS)',
    lastChecked: '27/05/2025 09:40',
    checkedBy: 'Adel B.',
    notes: 'Passage EDEN VERT 3D : Gel insecticide rémanent anti-blattes renouvelé.',
  },
  {
    id: 'pest_04',
    code: 'UV-01',
    location: 'Sas Livraison & Entrée Fournil',
    type: 'Désinsectiseur UV',
    status: 'Intact (RAS)',
    lastChecked: '27/05/2025 09:45',
    checkedBy: 'Adel B.',
    notes: 'Contrôle EDEN VERT 3D : Tube UV fonctionnel, bac récepteur nettoyé.',
  }
];

export const DEFAULT_PEST_CONTRACT: PestContractInfo = {
  companyName: 'EDEN VERT 3D (SARL MJC 3D)',
  contractNumber: 'CH-25-97',
  lastVisitDate: '08/06/2026',
  nextVisitDate: '08/09/2026',
  status: 'Actif & Conforme',
  technicianName: 'Jérémy CLAIRE (Tél: 02.35.03.84.59)',
  annualFeeHt: 540.0,
  passagesPerYear: 4,
  siret: '88004805300016',
  phone: '02.35.03.84.59',
};

// 🚚 Historique des Passages & Interventions EDEN VERT 3D
export const DEFAULT_PEST_INTERVENTIONS: PestIntervention[] = [
  {
    id: 'pest_int_01',
    passageNumber: 1,
    totalPassages: 4,
    date: '08/06/2026',
    invoiceNumber: 'F76-26-01207',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Renouvellement annuel 2026/2027)',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur', 'Fournil & Sas'],
    actions: [
      'Contrôle préventif et renouvellement du rodonticide anticoagulant dans les postes PVC',
      'Traitement de désinsectisation par application de gel insecticide rémanent anti-blattes aux zones stratégiques',
      'Contrôle du désinsectiseur UV Sas Livraison (tube & récepteur)',
    ],
    observations: 'Locaux et laboratoire en parfait état d’hygiène. Aucune trace de rongeurs vivants. Boîtes d’appâtage sécurisées réapprovisionnées.',
    status: 'Effectué & Conforme',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
  {
    id: 'pest_int_02',
    passageNumber: 4,
    totalPassages: 4,
    date: '30/03/2026',
    invoiceNumber: 'F76-26-00642',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Passage N°4 - Clôture Contrat 2025/2026)',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur', 'Réserve farine'],
    actions: [
      'Contrôle complet des postes PVC souris & rats',
      'Remplacement intégral des rodonticides consommés par molécule anticoagulante HACCP',
      'Renouvellement des points de gel anti-blattes sous réfrigérateur et four',
    ],
    observations: 'Postes PVC souris et rats : consommation forte constatée. Traitement curatif et préventif appliqué, renouvellement total des appâts.',
    status: 'Effectué & Conforme',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
  {
    id: 'pest_int_03',
    passageNumber: 3,
    totalPassages: 4,
    date: '15/12/2025',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Passage N°3 - Trimestre Hiver)',
    locations: ['Local commercial', 'Fournil & Sas', 'Laboratoire Pâtisserie'],
    actions: [
      'Contrôle d’activité hivernale',
      'Vérification des appâts rodonticides et gel',
      'Test de fonctionnement UV sas',
    ],
    observations: 'RAS - Appâts intacts à 80%, dépoussiérage des boîtes et renouvellement préventif.',
    status: 'Effectué & Conforme',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
  {
    id: 'pest_int_04',
    passageNumber: 2,
    totalPassages: 4,
    date: '18/09/2025',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Passage N°2 - Trimestre Automne)',
    locations: ['Local commercial', 'Fournil', 'Réserve farine'],
    actions: [
      'Contrôle des boîtes d’appâtage rongeurs',
      'Application préventive gel insecticide',
    ],
    observations: 'RAS - Très faible consommation en réserve farine, poste réarmé et sécurisé.',
    status: 'Effectué & Conforme',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
  {
    id: 'pest_int_05',
    passageNumber: 1,
    totalPassages: 4,
    date: '09/06/2025',
    invoiceNumber: 'F76-25-01041',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Passage N°1 - Mise en service Contrat)',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur', 'Fournil & Sas'],
    actions: [
      'Installation et numérotation des postes PVC sécurisés P-01 à P-04',
      'Mise en place de rodonticide anticoagulant homologué HACCP',
      'Traitement de désinsectisation par pulvérisation d’un insecticide contact à fort pouvoir rémanent + gel anti-blattes cuisine',
    ],
    observations: 'Mise en place du plan anti-nuisibles initial conforme DDPP. Boîtes d’appâtage étiquetées et fixées.',
    status: 'Effectué & Conforme',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
  {
    id: 'pest_int_06',
    passageNumber: 2,
    totalPassages: 4,
    date: '08/09/2026',
    contractNumber: 'CH-25-97',
    technician: 'Jérémy CLAIRE (Agréé Certibiocide)',
    type: 'Dératisation & Désinsectisation (Passage N°2 - Contrat 2026/2027)',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur', 'Fournil & Sas'],
    actions: [
      'Contrôle trimestriel programmé',
      'Vérification consommation rodonticides et rémanence gel',
      'Inspection sas et réserve',
    ],
    observations: 'Visite de maintenance trimestrielle planifiée conforme au calendrier du contrat.',
    status: 'Planifié',
    amountHt: 135.0,
    amountTtc: 162.0,
  },
];

// 🧾 Factures Officielles EDEN VERT 3D (SARL MJC 3D)
export const DEFAULT_PEST_INVOICES: PestInvoice[] = [
  {
    id: 'inv_eden_26_01207',
    invoiceNumber: 'F76-26-01207',
    invoiceDate: '09/06/2026',
    saleDate: '08/06/2026',
    contractNumber: 'CH-25-97',
    passageLabel: 'Passage N°1 sur 4 (Renouvellement 2026/2027)',
    object: 'DERATISATION',
    designation: 'Dératisation / Désinsectisation - CONTRAT HYGIENE',
    qty: 1,
    unitPriceHt: 135.0,
    totalHt: 135.0,
    tvaRate: 20,
    tvaAmount: 27.0,
    totalTtc: 162.0,
    isPaid: true,
    paymentMethod: 'Comptant (Virement bancaire)',
    paymentDueDate: '09/06/2026',
    bankName: 'BPVF MANTES GAMBETTA',
    iban: 'FR76 1870 7000 1231 6216 5787 808',
    bic: 'CCBPFRPPVER',
    deratisationText: 'Traitement préventif de l’établissement contre les rongeurs (rats et souris) réalisé à l’aide d’un rodonticide approprié à base d’une molécule anticoagulante conformément aux normes HACCP. Tous les postes seront contrôlés par nos techniciens et les produits consommés ou non seront changés à chaque passage.',
    desinsectisationText: 'Traitement de désinsectisation contre les blattes par la mise en place d’un gel insecticide à fort pouvoir rémanent placé aux endroits stratégiques de passage des nuisibles. Note : le 1er passage est un traitement de désinsectisation par pulvérisation d’un insecticide contact à fort pouvoir rémanent.',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur'],
    observations: 'Contrat annuel d’hygiène renouvelé. Tous nos techniciens sont agréés Certibiocide.',
  },
  {
    id: 'inv_eden_26_00642',
    invoiceNumber: 'F76-26-00642',
    invoiceDate: '31/03/2026',
    saleDate: '30/03/2026',
    contractNumber: 'CH-25-97',
    passageLabel: 'Passage(s) N°4 | sur un total de 4 passage(s)',
    object: 'DERATISATION',
    designation: 'Dératisation / Désinsectisation - CONTRAT HYGIENE',
    qty: 1,
    unitPriceHt: 135.0,
    totalHt: 135.0,
    tvaRate: 20,
    tvaAmount: 27.0,
    totalTtc: 162.0,
    isPaid: true,
    paymentMethod: 'Comptant (Virement bancaire)',
    paymentDueDate: '31/03/2026',
    bankName: 'BPVF MANTES GAMBETTA',
    iban: 'FR76 1870 7000 1231 6216 5787 808',
    bic: 'CCBPFRPPVER',
    deratisationText: 'Traitement préventif de l’établissement contre les rongeurs (rats et souris) réalisé à l’aide d’un rodonticide approprié à base d’une molécule anticoagulante conformément aux normes HACCP. Tous les postes seront contrôlés par nos techniciens et les produits consommés ou non seront changés à chaque passage.',
    desinsectisationText: 'Traitement de désinsectisation contre les blattes par la mise en place d’un gel insecticide à fort pouvoir rémanent placé aux endroits stratégiques de passage des nuisibles. Note : le 1er passage est un traitement de désinsectisation par pulvérisation d’un insecticide contact à fort pouvoir rémanent.',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur'],
    observations: 'Postes pvc souris consommation forte • Postes pvc rats consommation forte. Montant commande HT : 540,00 € • Montant restant HT : 0,00 € (Soldé).',
  },
  {
    id: 'inv_eden_25_01041',
    invoiceNumber: 'F76-25-01041',
    invoiceDate: '11/06/2025',
    saleDate: '09/06/2025',
    contractNumber: 'CH-25-97',
    passageLabel: 'Passage(s) N°1 | sur un total de 4 passage(s)',
    object: 'DERATISATION',
    designation: 'Dératisation / Désinsectisation - CONTRAT HYGIENE',
    qty: 1,
    unitPriceHt: 135.0,
    totalHt: 135.0,
    tvaRate: 20,
    tvaAmount: 27.0,
    totalTtc: 162.0,
    isPaid: true,
    paymentMethod: 'Comptant (Virement bancaire)',
    paymentDueDate: '11/06/2025',
    bankName: 'BPVF MANTES GAMBETTA',
    iban: 'FR76 1870 7000 1231 6216 5787 808',
    bic: 'CCBPFRPPVER',
    deratisationText: 'Traitement préventif de l’établissement contre les rongeurs (rats et souris) réalisé à l’aide d’un rodonticide approprié à base d’une molécule anticoagulante conformément aux normes HACCP. Tous les postes seront contrôlés par nos techniciens et les produits consommés ou non seront changés à chaque passage.',
    desinsectisationText: 'Traitement de désinsectisation contre les blattes par la mise en place d’un gel insecticide à fort pouvoir rémanent placé aux endroits stratégiques de passage des nuisibles. Note : le 1er passage est un traitement de désinsectisation par pulvérisation d’un insecticide contact à fort pouvoir rémanent.',
    locations: ['Local commercial', 'Cuisine - four et réfrigérateur'],
    observations: 'Passage initial N°1 du contrat annuel CH-25-97. Commande HT 540,00 €. Tous nos techniciens sont agréés Certibiocide.',
  },
];


// 🗑️ Suivi des Déchets & Invendus
export const DEFAULT_WASTE_LOGS: WasteLog[] = [
  {
    id: 'w_01',
    productName: 'Pâtons Baguettes Tradition (Sur-fermentation)',
    category: 'Pâtons / Pâte',
    quantityKg: 4.5,
    reason: 'Sur-fermentation',
    discardedAt: '18/08/2026 12:00',
    discardedBy: 'Hamza M.',
    method: 'Biodéchets Dédiés',
    notes: 'Pâte trop acide suite à coupure chambre de pousse.',
  },
  {
    id: 'w_02',
    productName: 'Reste Crème Pâtissière Chocolat J+2',
    category: 'Pâtisseries',
    quantityKg: 1.2,
    reason: 'DLC Dépassée',
    discardedAt: '19/08/2026 19:00',
    discardedBy: 'Said dz',
    method: 'Destruction Volontaire',
    notes: 'Dépassement des 48h réglementaires - jeté immédiatement.',
  }
];

// 🛡️ Points de Contrôle DDPP Préfecture (Grille Officielle Alim'confiance)
export const DEFAULT_DDPP_AUDIT_POINTS: DdpAuditPoint[] = [
  {
    id: 'ddpp_01',
    category: 'Lutte Nuisibles',
    title: 'Absence totale d’insectes et rongeurs (Diviseuse & Bacs hermétiques)',
    description: 'Aucun insecte dans la diviseuse à pain, les bacs de farine/céréales étanches, DEIV fonctionnel.',
    fineRiskEur: 1500,
    isImmediateClosureRisk: true,
    status: 'Conforme',
    correctiveAdvice: 'Aspiration hebdomadaire de la farine dans la diviseuse et stockage en bacs Gilac étanches.',
  },
  {
    id: 'ddpp_02',
    category: 'Hygiène Locaux & Lave-Mains',
    title: 'Produits de désinfection homologués contact alimentaire (EN 1276 / EN 13697)',
    description: 'Présentation obligatoire des bidons Suma Bac D10 / Sirafan et Fiches Techniques en cours de validité.',
    fineRiskEur: 1500,
    isImmediateClosureRisk: true,
    status: 'Conforme',
    correctiveAdvice: 'Consulter l’onglet « Produits Agréés » pour montrer les attestations normées à l’inspecteur.',
  },
  {
    id: 'ddpp_03',
    category: 'PMS & Formation',
    title: 'Affichage obligatoire des 14 Allergènes (100% Viennoiseries incluses)',
    description: 'Croissants, pains au chocolat, brioches, chaussons et snacking clairement répertoriés.',
    fineRiskEur: 750,
    isImmediateClosureRisk: false,
    status: 'Conforme',
    correctiveAdvice: 'Imprimer la matrice officielle depuis l’onglet « Allergènes » et l’afficher en boutique.',
  },
  {
    id: 'ddpp_04',
    category: 'Traçabilité & DLC',
    title: 'Traçabilité intégrale des denrées & Bons de Livraison (Zéro produit anonyme)',
    description: 'Toute denrée entamée doit porter sa DLC secondaire (J+3) et chaque lot doit avoir son BL.',
    fineRiskEur: 1500,
    isImmediateClosureRisk: true,
    status: 'Conforme',
    correctiveAdvice: 'Photographier chaque BL à la livraison et coller une étiquette DLC 2nde sur chaque bac.',
  },
  {
    id: 'ddpp_05',
    category: 'Chaîne du Froid',
    title: 'Relevés matin & soir des températures (< +4°C en froid positif, -18°C négatif)',
    description: 'Contrôle quotidien obligatoire des chambres froides, congélateurs dégivrés et vitrines sandwichs.',
    fineRiskEur: 1500,
    isImmediateClosureRisk: true,
    status: 'Conforme',
    correctiveAdvice: 'Valider les 2 relevés quotidiens dans l’onglet « Relevés » sur la tablette.',
  },
  {
    id: 'ddpp_06',
    category: 'Hygiène Locaux & Lave-Mains',
    title: 'Poste lave-mains dédié (Commande non manuelle + Savon EN 1499 + Papier jetable)',
    description: 'Lave-mains obligatoire dans chaque zone de travail. Interdiction formelle des torchons tissu.',
    fineRiskEur: 750,
    isImmediateClosureRisk: false,
    status: 'Conforme',
    correctiveAdvice: 'Vérifier la recharge de savon bactéricide et le rouleau d’essuie-mains chaque matin.',
  },
  {
    id: 'ddpp_07',
    category: 'Hygiène Locaux & Lave-Mains',
    title: 'Plan de Nettoyage (PND) : Sols décapés, pétrin, cercles à tartes, machine granité',
    description: 'Absence totale de résidus organiques ou de taches de peinture sur les carrelages et le matériel.',
    fineRiskEur: 1500,
    isImmediateClosureRisk: false,
    status: 'Conforme',
    correctiveAdvice: 'Émarger les tâches de nettoyage quotidiennes dans l’onglet « Nettoyage » avec photos.',
  },
  {
    id: 'ddpp_08',
    category: 'PMS & Formation',
    title: 'Contrat anti-nuisibles 3D actif (4 passages) & Attestations formation HACCP',
    description: 'Contrat EDEN VERT 3D à jour avec bons d’intervention et registre de formation du personnel.',
    fineRiskEur: 3000,
    isImmediateClosureRisk: false,
    status: 'Conforme',
    correctiveAdvice: 'Présenter le volet Nuisibles 3D et le certificat HACCP exportable en PDF.',
  },
];

// 🧴 Produits Agréés & Homologués Contact Alimentaire (Normes EN 1276 / EN 13697)
export const DEFAULT_APPROVED_PRODUCTS: ApprovedProduct[] = [
  {
    id: 'prod_suma_d10',
    name: 'Suma Bac D10',
    brand: 'Diversey',
    category: 'Surfaces & Inox',
    norms: ['EN 1276 (Bactéricide)', 'EN 1650 (Lévuricide)', 'EN 13697 (Surfaces)', 'Contact Alimentaire'],
    usage: 'Dégraissant désinfectant concentré pour toutes les surfaces de préparation alimentaire.',
    targetEquipment: ['Diviseuse à pain', 'Cuve pétrin spirale', 'Tours réfrigérés inox', 'Cercles à tartes', 'Chariots de cuisson', 'Bacs à farine'],
    dosage: '2% (20 ml par Litre d’eau tiède)',
    dilutionPercent: 2,
    contactTime: '5 minutes',
    needsRinse: true,
    officialRef: 'Diversey Ref: 7513063 / Homologation Min. Agriculture',
    instructions: [
      '1. Racler les dépôts et résidus de pâte / farine au préalable.',
      '2. Pulvériser ou appliquer la solution diluée à 2% sur l’équipement.',
      '3. Laisser agir 5 minutes pour garantir la destruction bactérienne (EN 1276).',
      '4. Rincer à l’eau claire potable à l’aide d’une lavette propre et laisser sécher.',
    ],
    precautions: 'Port de gants recommandé. Ne pas mélanger avec de la javel ou des acides.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
  {
    id: 'prod_sirafan_speed',
    name: 'Sirafan Speed',
    brand: 'Ecolab',
    category: 'Petit Matériel & Sans Rinçage',
    norms: ['EN 1276', 'EN 1650', 'EN 13697', 'Prêt à l’emploi', 'Sans Rinçage'],
    usage: 'Désinfectant rapide à base d’alcool pour petit matériel et désinfection intermédiaire en cours de journée.',
    targetEquipment: ['Couteaux de tour & lames', 'Lame de trancheuse à pain', 'Cercles à tartes & emporte-pièces', 'Sondes thermomètres', 'Balances & claviers'],
    dosage: 'Prêt à l’emploi (Pur en pulvérisation)',
    dilutionPercent: 100,
    contactTime: '60 secondes',
    needsRinse: false,
    officialRef: 'Ecolab Ref: 9036710 / Formulation sans rinçage',
    instructions: [
      '1. Nettoyer la surface pour enlever les souillures grossières.',
      '2. Pulvériser Sirafan Speed pur à 20-30 cm de distance.',
      '3. Laisser sécher à l’air libre pendant 1 minute.',
      '4. Aucun rinçage nécessaire, réutilisation immédiate du matériel.',
    ],
    precautions: 'Produit inflammable (alcool). Ne pas pulvériser sur une surface chaude ou près d’une flamme.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
  {
    id: 'prod_suma_d35',
    name: 'Suma Break Up D3.5',
    brand: 'Diversey',
    category: 'Sols & Plonge Surpuissant',
    norms: ['Décapant Dégraissant Alcalin', 'Contact Alimentaire', 'Surfaces très grasses'],
    usage: 'Nettoyage lourd et décapage des sols carrelés, faïences en plonge et grilles d’évacuation.',
    targetEquipment: ['Sol plonge & caniveaux', 'Faïence murale plonge', 'Sol fournil & dessous de four', 'Plaques et grilles très encrassées'],
    dosage: '3% à 5% (30 à 50 ml / Litre d’eau chaude)',
    dilutionPercent: 4,
    contactTime: '10 à 15 minutes',
    needsRinse: true,
    officialRef: 'Diversey Ref: 7508282 / Formule anti-graisses cuites',
    instructions: [
      '1. Balayer et éliminer les débris grossiers.',
      '2. Appliquer la solution chaude sur le carrelage et la faïence.',
      '3. Brosser ou frotter avec un balai brosse ou gratteur de sol.',
      '4. Laisser agir 10 minutes puis rincer abondamment à l’eau claire et racler.',
    ],
    precautions: 'Produit alcalin puissant : port de gants et lunettes de protection obligatoire.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
  {
    id: 'prod_suma_d4a',
    name: 'Suma San D4a / Pastilles Sanichlor',
    brand: 'Diversey',
    category: 'Machine à Granité & Circuits',
    norms: ['EN 1276', 'EN 1650', 'Pastilles désinfectantes chlorées alimentaires'],
    usage: 'Désinfection par trempage et circulation des machines à granité, machines à chantilly et circuits de boissons.',
    targetEquipment: ['Machine à granité', 'Cuve et robinets de distribution granité', 'Machine à glace / chantilly', 'Pichets et circuits fermés'],
    dosage: '1 pastille pour 10 Litres d’eau froide (100 ppm de chlore actif)',
    dilutionPercent: 1,
    contactTime: '15 minutes',
    needsRinse: true,
    officialRef: 'Diversey Ref: 7511993 / Désinfection circuits boissons',
    instructions: [
      '1. Vidanger et démonter la cuve, les joints et les becs verseurs de la machine.',
      '2. Laver préalablement avec un détergent doux et rincer.',
      '3. Faire tremper les pièces démontées dans la solution Suma San pendant 15 minutes.',
      '4. Faire circuler la solution dans la machine puis rincer abondamment à l’eau potable.',
    ],
    precautions: 'Toujours utiliser dans de l’eau froide ou tiède (jamais chaude). Bien rincer.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
  {
    id: 'prod_anios_manugerm',
    name: 'Manugerm / Tork Savon Bactéricide',
    brand: 'Anios',
    category: 'Lave-Mains Bactéricide',
    norms: ['EN 1499 (Lavage hygiénique des mains)', 'Sans parfum allergisant', 'Testé sous contrôle médical'],
    usage: 'Lavage et désinfection hygiénique des mains à chaque prise de poste et changement de tâche.',
    targetEquipment: ['Lave-mains Laboratoire Pâtisserie', 'Lave-mains Fournil', 'Lave-mains Plonge', 'Sanitaires personnel'],
    dosage: '1 dose (2 ml pur sur mains mouillées)',
    dilutionPercent: 100,
    contactTime: '30 secondes',
    needsRinse: true,
    officialRef: 'Laboratoires Anios / Tork Premium Hygiene',
    instructions: [
      '1. Mouiller les mains et les poignets à l’eau tiède.',
      '2. Déposer 1 pression de savon au creux des mains.',
      '3. Frotter énergiquement pendant 30 secondes (paumes, dos, entre les doigts, ongles).',
      '4. Rincer à l’eau claire et sécher avec un papier essuie-mains à usage unique.',
    ],
    precautions: 'Usage externe uniquement. Fermer le robinet avec le papier ou la commande au pied/genou.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
  {
    id: 'prod_gilac_bacs',
    name: 'Bacs Hermétiques & Boîtes Étanche Gilac',
    brand: 'Gilac',
    category: 'Stockage Hermétique Anti-Insectes',
    norms: ['Norme CE 1935/2004 Contact Alimentaire', 'Couvercle à joint étanche anti-nuisibles', 'Polyéthylène haute densité'],
    usage: 'Stockage étanche et hermétique des farines, sucres, céréales et graines pour empêcher l’accès des insectes.',
    targetEquipment: ['Bac à farine 80L avec couvercle', 'Bacs à céréales & graines', 'Boîtes de pépites de chocolat', 'Bacs de réserve sèche'],
    dosage: 'Matériel de stockage aux normes',
    contactTime: 'Permanent',
    needsRinse: false,
    officialRef: 'Gilac Plastiques Alimentaires Certifiés',
    instructions: [
      '1. Toujours maintenir le couvercle fermé après chaque pesée.',
      '2. Ne jamais rajouter de la farine neuve sur un fond sans avoir vidé et lavé le bac.',
      '3. Nettoyer et désinfecter le bac avec Suma Bac D10 avant chaque nouveau sac.',
    ],
    precautions: 'Inspecter les joints de fermeture régulièrement.',
    inStock: true,
    verifiedDate: '10/08/2026',
  },
];

// 🥐 Matrice des 14 Allergènes Majeurs (Règlement Européen INCO n°1169/2011)
export const DEFAULT_ALLERGENS: AllergenItem[] = [
  // --- VIENNOISERIES (Point relevé par la DDPP) ---
  {
    id: 'all_croissant',
    name: 'Croissant au Beurre AOP',
    category: 'Viennoiseries',
    description: 'Pâte levée feuilletée pur beurre de tradition.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)'],
    tracesPossible: ['Œufs', 'Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_pain_choc',
    name: 'Pain au Chocolat Pur Beurre',
    category: 'Viennoiseries',
    description: 'Feuilletage pur beurre avec 2 barres de chocolat noir 44%.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Soja (Lécithine)'],
    tracesPossible: ['Œufs', 'Fruits à coque (Amandes/Noisettes)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_pain_raisins',
    name: 'Pain aux Raisins / Escargot',
    category: 'Viennoiseries',
    description: 'Pâte levée feuilletée garnie de crème pâtissière maison et raisins secs.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs'],
    tracesPossible: ['Soja (Lécithine)', 'Sulfites (>10mg/kg)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_croissant_amandes',
    name: 'Croissant aux Amandes',
    category: 'Viennoiseries',
    description: 'Croissant imbibé au sirop et garni de crème d’amandes avec amandes effilées.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs', 'Fruits à coque (Amandes/Noisettes)'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_chausson_pommes',
    name: 'Chausson aux Pommes',
    category: 'Viennoiseries',
    description: 'Feuilletage pur beurre garni de compote de pommes locale.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)'],
    tracesPossible: ['Œufs', 'Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_brioche',
    name: 'Brioche Tressée / Individuelle',
    category: 'Viennoiseries',
    description: 'Pâte levée riche en beurre frais et œufs entiers dorée au jaune d’œuf.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_chouquettes',
    name: 'Chouquettes au Sucre Perlé',
    category: 'Viennoiseries',
    description: 'Pâte à choux légère cuite au four avec grains de sucre.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_suisse',
    name: 'Pain Suisse Pépites de Chocolat',
    category: 'Viennoiseries',
    description: 'Brioche feuilletée garnie de crème pâtissière et pépites de chocolat.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs', 'Soja (Lécithine)'],
    tracesPossible: ['Fruits à coque (Amandes/Noisettes)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },

  // --- PAINS & BAGUETTES ---
  {
    id: 'all_tradition',
    name: 'Baguette Tradition Française',
    category: 'Pains & Baguettes',
    description: 'Farine T65 sans additifs, fermentation lente sur levain.',
    allergens: ['Gluten (Blé/Seigle/Orge)'],
    tracesPossible: ['Graines de sésame'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_pain_cereales',
    name: 'Baguette / Pain aux Céréales',
    category: 'Pains & Baguettes',
    description: 'Mélange de farines avec graines de lin, tournesol, pavot et sésame.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Graines de sésame'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_pain_mie',
    name: 'Pain de Mie Maison',
    category: 'Pains & Baguettes',
    description: 'Pain moelleux au lait et beurre frais.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)'],
    tracesPossible: ['Œufs', 'Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },

  // --- PÂTISSERIES ---
  {
    id: 'all_eclair_choc',
    name: 'Éclair au Chocolat',
    category: 'Pâtisseries',
    description: 'Pâte à choux, crème pâtissière au chocolat noir, glaçage fondant.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs', 'Soja (Lécithine)'],
    tracesPossible: ['Fruits à coque (Amandes/Noisettes)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_tarte_fruits',
    name: 'Tartelette aux Fruits Frais',
    category: 'Pâtisseries',
    description: 'Fond sablé pur beurre, crème d’amandes, crème pâtissière et fruits frais.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs', 'Fruits à coque (Amandes/Noisettes)'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_paris_brest',
    name: 'Paris-Brest Praliné',
    category: 'Pâtisseries',
    description: 'Couronne de pâte à choux avec crème mousseline pralinée et amandes effilées.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs', 'Fruits à coque (Amandes/Noisettes)'],
    tracesPossible: ['Soja (Lécithine)'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },

  // --- SNACKING & SALÉ ---
  {
    id: 'all_sandwich_jambon',
    name: 'Sandwich Jambon Beurre Emmental',
    category: 'Snacking & Salé',
    description: 'Baguette tradition, beurre doux AOP, jambon supérieur, emmental grand affinage.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)'],
    tracesPossible: ['Moutarde', 'Graines de sésame'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_sandwich_thon',
    name: 'Sandwich Thon Crudités Mayonnaise',
    category: 'Snacking & Salé',
    description: 'Baguette tradition, thon germon émietté, mayonnaise maison, œuf dur, tomates, salade.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Poisson', 'Œufs', 'Moutarde'],
    tracesPossible: ['Lait & Lactose (Beurre/Crème)', 'Graines de sésame'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
  {
    id: 'all_quiche_lorraine',
    name: 'Quiche Lorraine Traditionnelle',
    category: 'Snacking & Salé',
    description: 'Pâte brisée pur beurre, lardons fumés, appareil à quiche œufs frais et crème.',
    allergens: ['Gluten (Blé/Seigle/Orge)', 'Lait & Lactose (Beurre/Crème)', 'Œufs'],
    tracesPossible: ['Moutarde'],
    lastUpdated: '12/08/2026',
    isHouseMade: true,
  },
];

export const STORAGE_KEYS = {
  USERS: 'sp_users',
  CURRENT_USER: 'sp_current_user',
  TEMPERATURE_TARGETS: 'sp_temp_targets',
  TEMPERATURE_RECORDS: 'sp_temp_records',
  CLEANING_TASKS: 'sp_cleaning_tasks',
  GOODS_RECEIPTS: 'sp_receipts',
  SECONDARY_DLC: 'sp_secondary_dlc',
  INCIDENTS: 'sp_incidents',
  PEST_STATIONS: 'sp_pest_stations',
  PEST_CONTRACT: 'sp_pest_contract',
  PEST_INTERVENTIONS: 'sp_pest_interventions',
  PEST_INVOICES: 'sp_pest_invoices',
  WASTE_LOGS: 'sp_waste_logs',
  DDPP_AUDIT_POINTS: 'sp_ddpp_audit_points',
  APPROVED_PRODUCTS: 'sp_approved_products',
  ALLERGENS: 'sp_allergens',
};

export function getStoredData<T>(key: string, defaultVal: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return defaultVal;
    const parsed = JSON.parse(raw);
    if (parsed === null || parsed === undefined) return defaultVal;
    if (Array.isArray(defaultVal) && !Array.isArray(parsed)) return defaultVal;
    if (typeof defaultVal === 'object' && !Array.isArray(defaultVal) && (typeof parsed !== 'object' || Array.isArray(parsed))) return defaultVal;
    return parsed as T;
  } catch {
    return defaultVal;
  }
}

export function setStoredData<T>(key: string, val: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(val));
  } catch (e) {
    console.error('Error saving localStorage', e);
  }
}
